/* V-Input Core FFI Bindings */

#ifndef VINPUT_CORE_H
#define VINPUT_CORE_H

#pragma once

/* Warning: This file is auto-generated by cbindgen. Do not edit manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * V-Input 命令类型
 */
typedef enum VInputVInputCommandType {
  /**
   * 提交文本
   */
  CommitText = 1,
  /**
   * 显示候选
   */
  ShowCandidate = 2,
  /**
   * 隐藏候选
   */
  HideCandidate = 3,
  /**
   * 错误消息
   */
  Error = 4,
  /**
   * 撤销文本
   */
  UndoText = 5,
  /**
   * 重试文本
   */
  RedoText = 6,
} VInputVInputCommandType;

/**
 * V-Input 事件类型
 */
typedef enum VInputVInputEventType {
  /**
   * 开始录音
   */
  StartRecording = 1,
  /**
   * 停止录音
   */
  StopRecording = 2,
  /**
   * 音频数据
   */
  AudioData = 3,
  /**
   * 识别结果
   */
  RecognitionResult = 4,
  /**
   * VAD 状态变化
   */
  VADStateChanged = 5,
  /**
   * 撤销请求
   */
  UndoRequest = 6,
  /**
   * 重试请求
   */
  RedoRequest = 7,
} VInputVInputEventType;

/**
 * FFI 结果码
 */
typedef enum VInputVInputFFIResult {
  /**
   * 成功
   */
  Success = 0,
  /**
   * 空指针错误
   */
  NullPointer = -1,
  /**
   * 无效参数
   */
  InvalidArgument = -2,
  /**
   * 初始化失败
   */
  InitFailed = -3,
  /**
   * 未初始化
   */
  NotInitialized = -4,
  /**
   * 内部错误
   */
  InternalError = -5,
  /**
   * 无数据可读
   */
  NoData = -6,
  /**
   * 音频错误
   */
  AudioError = -7,
} VInputVInputFFIResult;

/**
 * V-Input 命令（从 Rust Core -> Fcitx5）
 */
typedef struct VInputVInputCommand {
  /**
   * 命令类型
   */
  enum VInputVInputCommandType command_type;
  /**
   * 文本数据（UTF-8，以 null 结尾）
   */
  char *text;
  /**
   * 文本长度（不含 null）
   */
  uintptr_t text_len;
} VInputVInputCommand;

/**
 * 命令回调函数类型
 *
 * 当 Rust Core 生成命令时，直接调用此回调通知 C++ 插件
 * 参数: VInputCommand 指针（C++ 需要调用 vinput_command_free 释放）
 */
typedef void (*VInputVInputCommandCallback)(const struct VInputVInputCommand*);

/**
 * V-Input 事件（从 Fcitx5 -> Rust Core）
 */
typedef struct VInputVInputEvent {
  /**
   * 事件类型
   */
  enum VInputVInputEventType event_type;
  /**
   * 数据指针（可选）
   */
  const uint8_t *data;
  /**
   * 数据长度
   */
  uintptr_t data_len;
} VInputVInputEvent;

/**
 * 音频设备信息（FFI 兼容）
 */
typedef struct VInputVInputAudioDevice {
  /**
   * 设备 ID（需要调用者释放）
   */
  char *id;
  /**
   * 设备名称（需要调用者释放）
   */
  char *name;
  /**
   * 设备描述（需要调用者释放）
   */
  char *description;
  /**
   * 是否为默认设备
   */
  bool is_default;
} VInputVInputAudioDevice;

/**
 * 音频设备列表（FFI 兼容）
 */
typedef struct VInputVInputAudioDeviceList {
  /**
   * 设备数组指针
   */
  struct VInputVInputAudioDevice *devices;
  /**
   * 设备数量
   */
  uintptr_t count;
} VInputVInputAudioDeviceList;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * 初始化 V-Input Core
 */
enum VInputVInputFFIResult vinput_core_init(void);

/**
 * 关闭 V-Input Core
 */
enum VInputVInputFFIResult vinput_core_shutdown(void);

/**
 * 注册命令回调函数
 *
 * C++ 插件在初始化时调用此函数，注册回调以接收实时命令
 * 当 Rust Core 检测到句子结束时，会直接调用此回调
 */
enum VInputVInputFFIResult vinput_core_register_callback(VInputVInputCommandCallback callback);

/**
 * 发送事件到 V-Input Core
 */
enum VInputVInputFFIResult vinput_core_send_event(const struct VInputVInputEvent *event);

/**
 * 尝试接收命令（非阻塞）
 */
enum VInputVInputFFIResult vinput_core_try_recv_command(struct VInputVInputCommand *command);

/**
 * 释放命令资源
 */
void vinput_command_free(struct VInputVInputCommand *command);

/**
 * 获取版本字符串
 */
const char *vinput_core_version(void);

/**
 * 枚举音频输入设备
 *
 * # 返回值
 * 成功返回设备列表指针，失败返回 null
 * 调用者需要使用 vinput_audio_device_list_free 释放内存
 */
struct VInputVInputAudioDeviceList *vinput_enumerate_audio_devices(void);

/**
 * 释放音频设备列表
 */
void vinput_audio_device_list_free(struct VInputVInputAudioDeviceList *list);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* VINPUT_CORE_H */
